@OnlyBalds.Api.Api_HostAddress = https://localhost:7204

@ACCESS_JWT=*********************************

GET {{OnlyBalds.Api.Api_HostAddress}}/threads/
Accept: application/json
Authorization: Bearer {{ACCESS_JWT}}

###

GET {{OnlyBalds.Api.Api_HostAddress}}/posts/
Accept: application/json
Authorization: Bearer {{ACCESS_JWT}}

###