# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - OnlyBalds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-onlybalds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Generate build-info.html
        run: |
          pwd
          ls
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          echo "<html>" > ./OnlyBalds/wwwroot/build-info.html
          echo "<head><title>Build Info</title></head>" >> ./OnlyBalds/wwwroot/build-info.html
          echo "<body>" >> ./OnlyBalds/wwwroot/build-info.html
          echo "<h1>Build Info</h1>" >> ./OnlyBalds/wwwroot/build-info.html
          echo "<p><strong>Version:</strong> $COMMIT_HASH</p>" >> ./OnlyBalds/wwwroot/build-info.html
          echo "<p><strong>Date:</strong> $BUILD_DATE</p>" >> ./OnlyBalds/wwwroot/build-info.html
          echo "</body></html>" >> ./OnlyBalds/wwwroot/build-info.html

      - name: Build with dotnet
        run: cd OnlyBalds;dotnet build --configuration Release

      - name: dotnet publish
        run: cd OnlyBalds;dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-onlybalds:
    runs-on: ubuntu-latest
    needs: build-onlybalds
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OnlyBalds'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D4F63BD79A1242D9B42CC4787E2F68A1 }}

  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: cd OnlyBalds.Api;dotnet build --configuration Release

      - name: dotnet publish
        run: cd OnlyBalds.Api;dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ${{env.DOTNET_ROOT}}/myapi

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-api
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OnlyBaldsApi'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7CD52F73A6894D0E958DFAFD60FA3651 }}