# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - OnlyBalds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-onlybalds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-onlybalds:
    runs-on: ubuntu-latest
    needs: build-onlybalds
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEA97DA877664239836A235721EFFAC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_64FD9CFEDFCB45C99FB2000C6BCAF37D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9945805778864D0FAAF184F73865EFC6 }}

      - name: Deploy to Azure Web App - OnlyBalds
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OnlyBalds'
          slot-name: 'Production'
          package: .

  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Navigating to api directory
        run: cd OnlyBalds.Api

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-api
          path: ${{env.DOTNET_ROOT}}/myapi

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-api
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-api.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-api

      - name: Login to Azure (reusing session)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23CA590FF6A04077A5D9272C7E6F32EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_430298B848E94F68AD048388BAD7E01F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D59F3A26C4074B6593C0E3F3EA4B8768 }}

      - name: Deploy to another Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OnlyBaldsApi'  # Replace 'AnotherApp' with the actual name of the second Azure App Service
          slot-name: 'Production'    # Adjust the slot name if needed
          package: .
