# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - OnlyBalds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-onlybalds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Generate build-info.html
        run: |
          pwd
          ls
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          echo "<html>" > wwwroot/build-info.html
          echo "<head><title>Build Info</title></head>" >> wwwroot/build-info.html
          echo "<body>" >> wwwroot/build-info.html
          echo "<h1>Build Info</h1>" >> wwwroot/build-info.html
          echo "<p><strong>Version:</strong> $COMMIT_HASH</p>" >> wwwroot/build-info.html
          echo "<p><strong>Date:</strong> $BUILD_DATE</p>" >> wwwroot/build-info.html
          echo "</body></html>" >> wwwroot/build-info.html

      - name: Build with dotnet
        run: dotnet build -c Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-onlybalds:
    runs-on: ubuntu-latest
    needs: build-onlybalds
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_02CE699C522A4743A4CCE9F4CA01DB49 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6E95F735D1BF46E6B33F9CEDFEB94768 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E89DCEE49AAF45FDBDE4EAFD65ED6148 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OnlyBalds'
          slot-name: 'Production'
          package: .