name: Secrets Scan

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Run Gitleaks
        run: |
          gitleaks detect \
            --config .gitleaks.toml \
            --redact \
            --exit-code=2 \
            --report-format=sarif \
            --report-path=results.sarif \
            --log-level=debug \
            --verbose
